name: crop-recommendation
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - pip=23.3.1
  - pip:
      - numpy==1.26.4
      - pandas==2.2.1
      - ipykernel==6.29.4
      - ipython==8.18.1
      - jupyter_client==8.6.1
      - jupyter_core==5.7.2
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - pyarrow==15.0.2
